server:
  port: 8989
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: root
  mvc:
    view:
      prefix: /
      suffix: .jsp
  # 上传文件大小限制
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    host: 192.168.72.6
    port: 7000
    database: 0
    jedis:
      pool:
        max-wait: -1
        max-active: 8
        max-idle: 8
        min-idle: 0

mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: com/baizhi/mapper/*.xml

logging:
  level:
    root: info
    com.baizhi.dao: debug